name: Guestbook
description: Leave a short note or feedback
title: "[Guestbook]"
labels: ["guestbook"]

body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for stopping by 👋  
        Write a short note or feedback below.  
        **Your GitHub username will be shown automatically.**

  - type: textarea
    attributes:
      label: Message
      placeholder: "Clean site. Maybe add X."
    validations:
      required: true
