name: Guestbook
description: Leave short feedback or a note
title: "[Guestbook] "
labels: ["guestbook"]
body:
  - type: textarea
    attributes:
      label: Message
      placeholder: "Your Message and name aswell"
    validations:
      required: true
